version: '3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/research123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=research123
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  neo4j_data: